### ISSUE TITLE
In Logseq version 0.10.8, the plugin has become invalid.

### ISSUE THREAD

**Issue by msjsc001** [studyduck/logseq-save-scrollbar-position#7]
Dear developer, the plugin has become invalid in Logseq version 0.10.8. As a long-term user, I hope this issue can be resolved.

Additionally, I suggest setting up a dedicated note within Logseq to record the location information of the opened pages. That way, when the notes are reindexed or reopened, the plugin will be able to remember the previous positions.

**Comment by EllisMorrow** [comment]
Restore after uninstalling and reinstalling the plugin. (This could be due to a potential plugin failure caused by changing the library location and re-indexing.)
